### ISSUE TITLE
ctags use

### ISSUE THREAD

**Issue by lumi0** [SoftSec-KAIST/TikNib#8]
**2. Extract function type information for type features.**
By utilizing ctags, this will extract type information. This will add abstract_args_type and abstract_ret_type into the previously created .pickle file.
python helper/extract_functype.py \
    --source_list "example/source_list.txt" \
    --input_list "example/input_list_find.txt" \
    --ctags_dir "data/ctags" \
    --threshold 1

Does ctags_dir "data/ctags"  mean the directory where I install ctags? But it doesn't add abstract_args_type and abstract_ret_type into the .pickle file.

**Comment by 0xdkay** [comment]
Hi @lumi0 , the `--ctags_dir` directory is where the ctags information of the source files (given by `--source_list`) will be stored.

For the output issue, please check if you give the correct suffix for the `.pickle` file. See [here](https://github.com/SoftSec-KAIST/TikNib/blob/master/helper/extract_functype.py#L25).

Otherwise, please describe your detailed steps so that I can reproduce it.

Thanks!

**Comment by lumi0** [comment]
收到

**Comment by lumi0** [comment]
Thank you! The output issue is successfully solved. 

But the --ctags_dir directory is still empty. I have downloaded the gnu_packages and put them in the directory where 
--source_list indicates.

**Comment by 0xdkay** [comment]
Glad you addressed it. For the ctags issue, could you check if
1) `--source_list` is the source file that **contains** the list of source directories, and
2) the `ctags` command is available in your machine?

**Comment by lumi0** [comment]
收到
