### ISSUE TITLE
About features extracted by IDApro

### ISSUE THREAD

**Issue by yanyou426** [SoftSec-KAIST/TikNib#9]
Hello, when I extract features of binaries, I found the number of keys in ['feature'] of each function is not the same. Is it something wrong with me?

**Comment by 0xdkay** [comment]
Hi @yanyou426, thanks for your interest.

The number of features can be different for each function because not all features can be extracted from each function.
Therefore, when calculating the ROC AUC, we initialized a numpy array that will contain feature values with zeros ([code](https://github.com/SoftSec-KAIST/TikNib/blob/master/helper/test_roc.py#L405)).
Then, we filled the array with the extracted feature values ([code](https://github.com/SoftSec-KAIST/TikNib/blob/master/helper/test_roc.py#L413)), considering the unextracted feature value as zero.

**Comment by yanyou426** [comment]
Thank u for the reply!!
